-- Tier 1 blueprint editoriali
-- Volumi aggregati con varianti sovrapposte: usare solo per prioritizzazione.

INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-iphone','eSIM su iPhone: modelli compatibili e configurazione','guide','Compatibilità','informational',1,'iphone dual sim',5000,25850,236,63.6,4.66,'planned','iphone dual sim | e sim iphone | iphone dual sim fisica | esim iphone 15 | esim iphone | iphone e sim | esim iphone 12 | esim iphone 13 | esim iphone 11 | iliad esim iphone | iphone 12 mini esim | iphone 12 mini e sim');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-estero','eSIM per l’estero: come scegliere il piano','guide','Viaggio','commercial',1,'esim estero',5000,19600,14,97.0,3.98,'planned','esim estero | sim virtuale estero | esim internazionale | e sim estero | esim per estero | esim per l estero | migliori esim estero | esim viaggio | esim per viaggiare | esim viaggi | sim virtuale per estero | esim mondo');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-usa','Migliore eSIM per USA e Stati Uniti','destination','Destinazioni','commercial',1,'esim usa',5000,12700,20,95.1,4.96,'planned','esim usa | esim stati uniti | holafly new york | esim per usa | esim per stati uniti | e sim america | holafly sim usa | iphone usa esim | esim america latina | esim usa holafly | esim vodafone usa | esim internet usa');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('migliore-esim','Migliore eSIM per viaggiare: confronto e criteri','comparison','Confronti','commercial',1,'migliore esim',5000,12050,7,100.0,3.36,'planned','migliore esim | migliori esim | esim economica | esim piu economica | migliori esim estero | esim piu conveniente | esim migliori offerte');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-egitto','Migliore eSIM per l’Egitto','destination','Destinazioni','commercial',1,'esim egitto',5000,11500,5,100.0,3.28,'planned','esim egitto | e sim egitto | holafly egitto | esim per egitto | esim egitto vodafone');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('codice-sconto-holafly','Codice sconto Holafly: come verificare le promozioni','provider','Provider','transactional',1,'holafly codice sconto',5000,10000,2,97.0,3.22,'planned','holafly codice sconto | codice sconto holafly');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-albania','Migliore eSIM per l’Albania','destination','Destinazioni','commercial',1,'esim albania',5000,6500,4,100.0,4.83,'planned','esim albania | e sim albania | esim vodafone albania | airalo albania');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-come-funziona','eSIM: come funziona, vantaggi e limiti','guide','Fondamentali','informational',1,'esim come funziona',5000,5700,6,79.0,2.84,'planned','esim come funziona | sim virtuale come funziona | esim come funziona iphone | e sim iphone come funziona | esim vodafone come funziona | esim tim come funziona');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('airalo-recensioni','Airalo recensioni: pro, contro e affidabilità','provider','Provider','commercial',1,'airalo recensioni',5000,5600,4,69.0,4.99,'planned','airalo recensioni | airalo esim recensioni | airalo trustpilot | trustpilot airalo');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-giappone','Migliore eSIM per il Giappone','destination','Destinazioni','commercial',1,'esim giappone',5000,5500,2,100.0,3.96,'planned','esim giappone | holafly giappone');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-turchia','Migliore eSIM per la Turchia','destination','Destinazioni','commercial',1,'esim turchia',5000,5500,2,100.0,4.19,'planned','esim turchia | holafly turchia');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-thailandia','Migliore eSIM per la Thailandia','destination','Destinazioni','commercial',1,'esim thailandia',5000,5500,2,100.0,4.99,'planned','esim thailandia | e sim thailandia');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('airalo-come-funziona','Airalo: come funziona e come si attiva','provider','Provider','commercial',1,'airalo come funziona',5000,5100,3,91.3,4.95,'planned','airalo come funziona | airalo come funziona android | airalo funziona');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-svizzera','Migliore eSIM per la Svizzera','destination','Destinazioni','commercial',1,'e sim svizzera',5000,5000,1,100.0,4.64,'planned','e sim svizzera');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('holafly-come-funziona','Holafly: come funziona e come si attiva','provider','Provider','commercial',1,'holafly come funziona',5000,5000,1,100.0,2.22,'planned','holafly come funziona');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-samsung','eSIM su Samsung Galaxy: modelli compatibili','guide','Compatibilità','informational',1,'esim samsung',500,8600,161,60.6,4.75,'planned','esim samsung | e sim samsung | esim telefoni compatibili samsung | samsung e sim | esim s22 ultra | samsung galaxy esim | samsung galaxy watch esim | esim samsung s22 ultra | esim galaxy s22 ultra | samsung watch e sim | samsung galaxy s22 5g esim | s21 5g esim');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-xiaomi','eSIM su Xiaomi: modelli compatibili','guide','Compatibilità','informational',1,'xiaomi esim',500,6750,127,43.4,10.89,'planned','xiaomi esim | esim xiaomi 11t pro | xiaomi 11t pro 5g esim | xiaomi 12 t pro esim | xiaomi note 11 pro esim | xiaomi redmi esim | xiaomi 11 esim | esim xiaomi redmi note 10s | xiaomi 12 e sim | xiaomi mi 9 esim | esim xiaomi 12 | esim xiaomi 11 lite');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-telefoni-compatibili','Telefoni compatibili con eSIM: elenco e verifica','guide','Compatibilità','informational',1,'telefoni con esim',500,2600,7,96.7,1.07,'planned','telefoni con esim | telefoni che supportano esim | telefoni compatibili con esim | telefoni compatibili esim | esim telefoni compatibili | telefoni con e sim | esim telefoni compatibili 2022');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-online','eSIM online: acquisto, consegna e attivazione','guide','Acquisto','transactional',1,'esim online',500,2150,7,88.7,5.53,'planned','esim online | e sim online | esim windtre online | windtre esim online | esim online free | esim coopvoce online | esim online windtre');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-gratis','eSIM gratis: cosa è davvero gratuito','guide','Acquisto','commercial',1,'esim gratuita',500,1700,7,97.3,2.44,'planned','esim gratuita | esim gratis | esim online gratis | e sim gratis | gratis esim | esim gratis online | vodafone esim gratis');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('holafly-recensioni','Holafly recensioni: pro, contro e affidabilità','provider','Provider','commercial',1,'holafly esim recensioni',500,1550,4,82.5,3.24,'planned','holafly esim recensioni | recensioni holafly | holafly trustpilot | holafly opinioni');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-viaggio','eSIM da viaggio: quando conviene e come prepararla','guide','Viaggio','commercial',1,'esim viaggio',500,1500,3,99.0,3.87,'planned','esim viaggio | esim per viaggiare | esim viaggi');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-costi','Quanto costa una eSIM? Prezzi e costi da controllare','guide','Acquisto','commercial',1,'esim costi',500,1000,2,100.0,1.3,'planned','esim costi | esim prezzo');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-giga-illimitati','eSIM con dati illimitati: limiti reali e fair use','guide','Piani dati','commercial',1,'esim giga illimitati',500,500,1,99.0,2.33,'planned','esim giga illimitati');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-senza-abbonamento','eSIM senza abbonamento: piani prepagati da viaggio','guide','Piani dati','commercial',1,'esim senza abbonamento',500,500,1,100.0,1.47,'planned','esim senza abbonamento');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-solo-dati','eSIM solo dati: come funziona con chiamate e WhatsApp','guide','Piani dati','informational',1,'esim solo dati',500,500,1,100.0,1.83,'planned','esim solo dati');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-vs-sim-fisica','eSIM o SIM fisica: differenze, vantaggi e limiti','comparison','Fondamentali','informational',1,'esim fisica',500,500,1,100.0,1.51,'planned','esim fisica');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('airalo-vs-holafly','Airalo vs Holafly: confronto per tipo di viaggio','comparison','Confronti','commercial',1,'',0,0,0,0.0,0.0,'planned','');
