-- Tier 2 e Tier 3 blueprint editoriali
-- Volumi aggregati con varianti sovrapposte: usare solo per prioritizzazione.

INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-5g','eSIM 5G: compatibilità, rete e velocità','guide','Tecnologia','informational',2,'esim 5g',500,2250,36,59.5,3.84,'planned','esim 5g | samsung galaxy s22 5g esim | s21 5g esim | esim tim 5g | xiaomi 11t pro 5g esim | iliad esim 5g | e sim 5g | esim 5g vodafone | 5g e sim | esim redmi note 11 pro 5g | esim 5g tim | esim redmi note 10 5g');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-dubai-emirati','Migliore eSIM per Dubai ed Emirati Arabi','destination','Destinazioni','commercial',2,'esim dubai',500,1500,3,99.7,4.76,'planned','esim dubai | esim emirati arabi | holafly dubai');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-business','eSIM Business per aziende e trasferte','guide','Business','commercial',2,'esim business',500,1250,16,62.3,31.42,'planned','esim business | e sim business | esim business tim | tim esim business | esim wind business | tim business esim | esim tim business | vodafone business esim | e sim tim business | esim windtre business | esim business vodafone | vodafone esim business');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-android','eSIM su Android: compatibilità e configurazione','guide','Compatibilità','informational',2,'esim android',500,1150,5,86.8,3.17,'planned','esim android | android esim | e sim android | android e sim | android 12 esim');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-zanzibar','Migliore eSIM per Zanzibar','destination','Destinazioni','commercial',2,'esim zanzibar',500,600,3,99.0,5.0,'planned','esim zanzibar | airalo zanzibar | e sim zanzibar');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-oman','Migliore eSIM per l’Oman','destination','Destinazioni','commercial',2,'esim oman',500,550,2,100.0,3.88,'planned','esim oman | oman esim');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('ubigi-recensioni','Ubigi recensioni: come funziona e per chi conviene','provider','Provider','commercial',2,'ubigi recensioni',500,550,2,100.0,2.94,'planned','ubigi recensioni | esim ubigi');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-repubblica-dominicana','Migliore eSIM per la Repubblica Dominicana','destination','Destinazioni','commercial',2,'esim repubblica dominicana',500,500,1,100.0,4.04,'planned','esim repubblica dominicana');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('esim-operatori-italiani','eSIM degli operatori italiani: guida comparativa','comparison','Operatori italiani','commercial',3,'vodafone esim',5000,106700,301,62.6,11.36,'planned','vodafone esim | esim tim | e sim vodafone | esim vodafone | esim iliad | e sim iliad | tim esim | esim wind | windtre esim | esim windtre | very mobile esim | iliad esim');
INSERT OR REPLACE INTO page_blueprints (slug,title,page_type,cluster,search_intent,launch_tier,primary_keyword,primary_volume,aggregate_keyword_volume,keyword_count,competition_index_avg,max_bid_high_eur,status,top_keywords) VALUES ('travelesim-recensioni','Travel eSIM: recensioni e alternative','provider','Provider','commercial',3,'travelesim',500,500,1,99.0,5.9,'planned','travelesim');
