-- Pagine ad alta intenzione mantenute fuori dall'indice finché prezzi, reti,
-- fair use, hotspot e regole di attivazione non sono verificati.

INSERT OR REPLACE INTO pages(slug,page_type,title,meta_description,eyebrow,h1,direct_answer,intro,content_json,faq_json,source_links_json,primary_keyword,cluster,search_intent,status,featured,source_checked_at,published_at) VALUES
('esim-giappone','destination','Migliore eSIM per il Giappone | Senza Roaming','Pagina in revisione: piani e condizioni devono essere verificati.','In revisione','Migliore eSIM per il Giappone','La raccomandazione verrà pubblicata soltanto dopo la verifica dei piani attualmente disponibili.','Prezzo, dati, durata, rete, hotspot, fair use e attivazione devono essere datati e documentati.','[{"type":"callout","title":"Quality gate","text":"Non pubblicare finché i dati commerciali e le fonti non sono completi."}]','[]','[]','esim giappone','Destinazioni','commercial','review',0,'2026-07-16',NULL),
('esim-usa','destination','Migliore eSIM per USA e Stati Uniti | Senza Roaming','Pagina in revisione: piani e condizioni devono essere verificati.','In revisione','Migliore eSIM per USA e Stati Uniti','La raccomandazione verrà pubblicata soltanto dopo la verifica dei piani attualmente disponibili.','Prezzo, dati, durata, rete, hotspot, fair use e attivazione devono essere datati e documentati.','[{"type":"callout","title":"Quality gate","text":"Non pubblicare finché i dati commerciali e le fonti non sono completi."}]','[]','[]','esim usa','Destinazioni','commercial','review',0,'2026-07-16',NULL),
('esim-turchia','destination','Migliore eSIM per la Turchia | Senza Roaming','Pagina in revisione: piani e condizioni devono essere verificati.','In revisione','Migliore eSIM per la Turchia','La raccomandazione verrà pubblicata soltanto dopo la verifica dei piani attualmente disponibili.','Prezzo, dati, durata, rete, hotspot, fair use e attivazione devono essere datati e documentati.','[{"type":"callout","title":"Quality gate","text":"Non pubblicare finché i dati commerciali e le fonti non sono completi."}]','[]','[]','esim turchia','Destinazioni','commercial','review',0,'2026-07-16',NULL),
('esim-egitto','destination','Migliore eSIM per l’Egitto | Senza Roaming','Pagina in revisione: piani e condizioni devono essere verificati.','In revisione','Migliore eSIM per l’Egitto','La raccomandazione verrà pubblicata soltanto dopo la verifica dei piani attualmente disponibili.','Prezzo, dati, durata, rete, hotspot, fair use e attivazione devono essere datati e documentati.','[{"type":"callout","title":"Quality gate","text":"Non pubblicare finché i dati commerciali e le fonti non sono completi."}]','[]','[]','esim egitto','Destinazioni','commercial','review',0,'2026-07-16',NULL),
('esim-thailandia','destination','Migliore eSIM per la Thailandia | Senza Roaming','Pagina in revisione: piani e condizioni devono essere verificati.','In revisione','Migliore eSIM per la Thailandia','La raccomandazione verrà pubblicata soltanto dopo la verifica dei piani attualmente disponibili.','Prezzo, dati, durata, rete, hotspot, fair use e attivazione devono essere datati e documentati.','[{"type":"callout","title":"Quality gate","text":"Non pubblicare finché i dati commerciali e le fonti non sono completi."}]','[]','[]','esim thailandia','Destinazioni','commercial','review',0,'2026-07-16',NULL),
('esim-albania','destination','Migliore eSIM per l’Albania | Senza Roaming','Pagina in revisione: piani e condizioni devono essere verificati.','In revisione','Migliore eSIM per l’Albania','La raccomandazione verrà pubblicata soltanto dopo la verifica dei piani attualmente disponibili.','Prezzo, dati, durata, rete, hotspot, fair use e attivazione devono essere datati e documentati.','[{"type":"callout","title":"Quality gate","text":"Non pubblicare finché i dati commerciali e le fonti non sono completi."}]','[]','[]','esim albania','Destinazioni','commercial','review',0,'2026-07-16',NULL),
('esim-svizzera','destination','Migliore eSIM per la Svizzera | Senza Roaming','Pagina in revisione: piani e condizioni devono essere verificati.','In revisione','Migliore eSIM per la Svizzera','La raccomandazione verrà pubblicata soltanto dopo la verifica dei piani attualmente disponibili.','Prezzo, dati, durata, rete, hotspot, fair use e attivazione devono essere datati e documentati.','[{"type":"callout","title":"Quality gate","text":"Non pubblicare finché i dati commerciali e le fonti non sono completi."}]','[]','[]','e sim svizzera','Destinazioni','commercial','review',0,'2026-07-16',NULL),
('airalo-recensioni','provider','Airalo recensioni: pro, contro e affidabilità | Senza Roaming','Pagina in revisione: test, condizioni e fonti devono essere completati.','In revisione','Airalo recensioni: pro, contro e affidabilità','La recensione verrà pubblicata dopo aver separato esperienza diretta, dichiarazioni del provider e condizioni dei piani.','La disponibilità di destinazioni non basta per una recensione: servono test, assistenza, rimborsi, hotspot e fair use.','[{"type":"callout","title":"Quality gate","text":"Non pubblicare una recensione senza metodo, prove e fonti."}]','[]','[]','airalo recensioni','Provider','commercial','review',0,'2026-07-16',NULL),
('airalo-come-funziona','provider','Airalo: come funziona e come si attiva | Senza Roaming','Pagina in revisione: procedura e condizioni devono essere verificate.','In revisione','Airalo: come funziona e come si attiva','La procedura verrà pubblicata dopo la verifica delle istruzioni ufficiali e delle differenze tra i piani.','Installazione, attivazione, roaming, ricariche e assistenza devono essere documentati.','[{"type":"callout","title":"Quality gate","text":"Verificare ogni passaggio sulle fonti ufficiali."}]','[]','[]','airalo come funziona','Provider','commercial','review',0,'2026-07-16',NULL),
('holafly-recensioni','provider','Holafly recensioni: pro, contro e affidabilità | Senza Roaming','Pagina in revisione: test, condizioni e fonti devono essere completati.','In revisione','Holafly recensioni: pro, contro e affidabilità','La recensione verrà pubblicata dopo aver separato esperienza diretta, dichiarazioni del provider e condizioni dei piani.','La parola “illimitato” richiede una verifica specifica di fair use, velocità e hotspot.','[{"type":"callout","title":"Quality gate","text":"Non pubblicare una recensione senza metodo, prove e fonti."}]','[]','[]','holafly esim recensioni','Provider','commercial','review',0,'2026-07-16',NULL),
('holafly-come-funziona','provider','Holafly: come funziona e come si attiva | Senza Roaming','Pagina in revisione: procedura e condizioni devono essere verificate.','In revisione','Holafly: come funziona e come si attiva','La procedura verrà pubblicata dopo la verifica delle istruzioni ufficiali e delle differenze tra i piani.','Installazione, attivazione, roaming, fair use e assistenza devono essere documentati.','[{"type":"callout","title":"Quality gate","text":"Verificare ogni passaggio sulle fonti ufficiali."}]','[]','[]','holafly come funziona','Provider','commercial','review',0,'2026-07-16',NULL),
('airalo-vs-holafly','comparison','Airalo vs Holafly: confronto per tipo di viaggio | Senza Roaming','Pagina in revisione: piani equivalenti e condizioni devono essere confrontati.','In revisione','Airalo vs Holafly: confronto per tipo di viaggio','Il confronto verrà pubblicato soltanto usando destinazione, durata e profilo d’uso equivalenti.','Dati, fair use, hotspot, rete, attivazione, rimborso, assistenza e prezzo devono essere verificati nella stessa data.','[{"type":"callout","title":"Quality gate","text":"Non confrontare piani non equivalenti o dati raccolti in date diverse."}]','[]','[]','airalo vs holafly','Confronti','commercial','review',0,'2026-07-16',NULL);
